"""tabela de mao de obra

Revision ID: 724545657abf
Revises: 70c5909d47f3
Create Date: 2024-04-21 18:03:31.942705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724545657abf'
down_revision = '70c5909d47f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mao_de_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mao_de_obra_servico', 'servico', ['servico'], ['id'])

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_autorizacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('d_finalizacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('d_retirada', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_column('d_retirada')
        batch_op.drop_column('d_finalizacao')
        batch_op.drop_column('d_autorizacao')

    with op.batch_alter_table('mao_de_obra', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mao_de_obra_servico', type_='foreignkey')
        batch_op.drop_column('servico')

    # ### end Alembic commands ###
